/**
 * Google Drive Storage Integration Helper
 * ──────────────────────────────────────────────────────────────────────────────
 * Allows uploading binary image buffers or base64 images generated by the AI
 * or uploaded by the user to a Google Drive folder.
 * 
 * Credentials required in .env:
 *  - GOOGLE_DRIVE_ACCESS_TOKEN (OAuth 2.0 access token or service account token)
 *  - GOOGLE_DRIVE_FOLDER_ID (Optional: target folder ID to save uploads)
 */

const axios = require('axios');
const FormData = require('form-data');
const { Readable } = require('stream');

const GOOGLE_DRIVE_API_URL = 'https://www.googleapis.com/upload/drive/v3/files';
const ACCESS_TOKEN = process.env.GOOGLE_DRIVE_ACCESS_TOKEN;
const FOLDER_ID = process.env.GOOGLE_DRIVE_FOLDER_ID;

const isConfigured = () => ACCESS_TOKEN && !ACCESS_TOKEN.includes('placeholder');

/**
 * Convert base64 data URL to stream
 */
function base64ToStream(base64Data) {
  const matches = base64Data.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);
  if (!matches || matches.length !== 3) {
    throw new Error('Invalid base64 string format');
  }
  const buffer = Buffer.from(matches[2], 'base64');
  return {
    stream: Readable.from(buffer),
    mimeType: matches[1]
  };
}

/**
 * Upload an image to Google Drive
 * @param {string} source - Base64 Data URL, URL of an image, or local file path
 * @param {string} fileName - Destination file name
 * @returns {Promise<string|null>} - Returns the uploaded Google Drive File ID or null
 */
async function uploadToGoogleDrive(source, fileName = 'fb-auto-post-image.png') {
  if (!isConfigured()) {
    console.log('[google-drive] Skipping upload: GOOGLE_DRIVE_ACCESS_TOKEN is not configured.');
    return null;
  }

  try {
    const form = new FormData();
    let fileStream;
    let mimeType = 'image/png';

    if (source.startsWith('data:')) {
      // Handle Base64 source
      const parsed = base64ToStream(source);
      fileStream = parsed.stream;
      mimeType = parsed.mimeType;
    } else if (source.startsWith('http://') || source.startsWith('https://')) {
      // Handle URL source (Fetch stream)
      const imageRes = await axios.get(source, { responseType: 'stream' });
      fileStream = imageRes.data;
      mimeType = imageRes.headers['content-type'] || 'image/jpeg';
    } else {
      // Handle local file path
      const fs = require('fs');
      if (fs.existsSync(source)) {
        fileStream = fs.createReadStream(source);
        mimeType = 'image/jpeg'; // Default fallback mime
      } else {
        throw new Error('Local file path does not exist');
      }
    }

    // Google Drive Metadata
    const metadata = {
      name: fileName,
      mimeType: mimeType
    };
    if (FOLDER_ID) {
      metadata.parents = [FOLDER_ID];
    }

    form.append('metadata', JSON.stringify(metadata), { contentType: 'application/json' });
    form.append('file', fileStream, { filename: fileName, contentType: mimeType });

    console.log(`[google-drive] Initiating multipart upload to Drive: "${fileName}" (${mimeType})...`);
    
    const response = await axios.post(
      `${GOOGLE_DRIVE_API_URL}?uploadType=multipart&fields=id,name,webViewLink`,
      form,
      {
        headers: {
          ...form.getHeaders(),
          Authorization: `Bearer ${ACCESS_TOKEN}`,
        },
        timeout: 25000
      }
    );

    const fileId = response.data?.id;
    console.log(`[google-drive] Upload success! File ID: ${fileId}. Link: ${response.data?.webViewLink}`);
    return fileId;
  } catch (error) {
    const detail = error.response?.data || error.message;
    console.error('[google-drive] Error uploading to Drive:', detail);
    return null;
  }
}

/**
 * List image files in the configured Google Drive folder.
 * @param {number} limit - Maximum number of files to fetch
 * @returns {Promise<Array>} - List of file metadata objects {id, name, webContentLink, webViewLink}
 */
async function listFilesFromGoogleDrive(limit = 20) {
  if (!isConfigured()) {
    console.log('[google-drive] Skipping listFiles: GOOGLE_DRIVE_ACCESS_TOKEN is not configured.');
    return [];
  }

  try {
    let q = "mimeType startswith 'image/' and trashed = false";
    if (FOLDER_ID) {
      q += ` and '${FOLDER_ID}' in parents`;
    }

    console.log(`[google-drive] Listing files with query: "${q}"...`);
    const response = await axios.get('https://www.googleapis.com/drive/v3/files', {
      params: {
        q,
        pageSize: limit,
        fields: 'files(id, name, mimeType, webContentLink, webViewLink)',
      },
      headers: {
        Authorization: `Bearer ${ACCESS_TOKEN}`,
      },
      timeout: 15000,
    });

    return response.data?.files || [];
  } catch (error) {
    const detail = error.response?.data || error.message;
    console.error('[google-drive] Error listing files from Drive:', detail);
    return [];
  }
}

module.exports = {
  uploadToGoogleDrive,
  listFilesFromGoogleDrive,
  isConfigured
};
